# Generated by Django 5.1.2 on 2024-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0004_remove_cat_breed_remove_kitten_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.FileField(default='image.jpg', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='image',
            field=models.FileField(default='image.jpg', upload_to='documents'),
        ),
    ]
