# Generated by Django 5.1.2 on 2024-11-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0006_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(default='image.jpg', upload_to='documents')),
            ],
        ),
    ]
