# Generated by Django 5.1.2 on 2024-11-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0007_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
    ]
