# Generated by Django 5.1.2 on 2024-11-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0013_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('doctor', models.CharField(max_length=255)),
            ],
        ),
    ]
