# Generated by Django 5.1.2 on 2024-11-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0019_remove_payment_content_type_remove_payment_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
